# 🌾 RICE DATASET EXTRACTION PIPELINE

This notebook runs the standalone `DATASET_BUILDER/src/rice_dataset` pipeline.
Raw inputs must be one workbook row and one image per `M####` ID, with images directly in `1_Raw_Images`.

In [1]:
# [Section 1]: Mount Google Drive and locate PROJECT_ROOT
import os
from pathlib import Path

try:
    from google.colab import drive
    drive.mount("/content/drive")
except ImportError:
    pass

override = os.environ.get("RICAI_PROJECT_ROOT")
candidates = [Path(override)] if override else [
    Path.cwd(),
    *Path.cwd().parents,
    Path("/content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES"),
]
shortcut_root = Path("/content/drive/.shortcut-targets-by-id")
if not override and shortcut_root.exists():
    candidates.extend(sorted(shortcut_root.glob(
        "*/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES"
    )))
PROJECT_ROOT = next((
    candidate for candidate in candidates
    if (candidate / "DATASET_BUILDER/config/extraction_config.json").is_file()
), None)
if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "Cannot locate MAIN_SOURCES. Set RICAI_PROJECT_ROOT to the absolute project path."
    )
print(f"📂 PROJECT_ROOT: {PROJECT_ROOT}")

Mounted at /content/drive
📂 PROJECT_ROOT: /content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES

In [2]:
# [Section 2 & 3]: Add package path and install runtime dependencies
import sys

src_dir = PROJECT_ROOT / "DATASET_BUILDER" / "src"
if str(src_dir) not in sys.path:
    sys.path.insert(0, str(src_dir))

!pip install -q ultralytics sahi tensorflow openpyxl pandas numpy opencv-python

import torch
print(f"⚡ PyTorch Version: {torch.__version__}")
print(f"🎮 CUDA Available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"   Device: {torch.cuda.get_device_name(0)}")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 37.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.9/151.9 kB 17.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 kB 13.0 MB/s eta 0:00:00
⚡ PyTorch Version: 2.11.0+cu128
🎮 CUDA Available: True
   Device: Tesla T4

In [3]:
# [Section 4]: Load and Display Validated Extraction Config
from rice_dataset.config import ExtractionConfig

config_file = PROJECT_ROOT / "DATASET_BUILDER" / "config" / "extraction_config.json"
config = ExtractionConfig.from_file(config_file, project_root_override=PROJECT_ROOT)

print("📋 Loaded Extraction Configuration:")
print(f"   - Contract Version  : {config.contract_version}")
print(f"   - SAHI Slice Size   : {config.sahi_slice_size}")
print(f"   - SAHI Overlap      : {config.sahi_overlap_ratio}")
print(f"   - CNN Whole Thresh  : {config.cnn_whole_confidence}")
print(f"   - Physical Packing  : {config.physical_packing_fraction}")
print(f"   - Hybrid Packing    : {config.trained_hybrid_packing_fraction}")
print(f"   - Thickness Ratio   : {config.whole_grain_thickness_ratio}")

📋 Loaded Extraction Configuration:
   - Contract Version  : code-main-2026-09-22
   - SAHI Slice Size   : 640
   - SAHI Overlap      : 0.25
   - CNN Whole Thresh  : 0.9
   - Physical Packing  : 0.55
   - Hybrid Packing    : 0.62
   - Thickness Ratio   : 0.8

In [4]:
# [Section 5]: Preflight Model Files & Paths
yolo_path = config.get_resolved_yolo_model_path()
cnn_path = config.get_resolved_cnn_model_path()
workbook_path = config.get_resolved_workbook_path()
images_dir = config.get_resolved_raw_images_dir()

print("🔍 Verifying Paths:")
print(f"   - YOLO Model : {'✅' if yolo_path.exists() else '❌'} {yolo_path}")
print(f"   - CNN Model  : {'✅' if cnn_path.exists() else '❌'} {cnn_path}")
print(f"   - Workbook   : {'✅' if workbook_path.exists() else '❌'} {workbook_path}")
print(f"   - Images Dir : {'✅' if images_dir.exists() else '❌'} {images_dir}")

assert yolo_path.exists(), f"Missing YOLO model at {yolo_path}"
assert cnn_path.exists(), f"Missing CNN model at {cnn_path}"
assert workbook_path.exists(), f"Missing Workbook at {workbook_path}"
assert images_dir.exists(), f"Missing Images Dir at {images_dir}"

🔍 Verifying Paths:
   - YOLO Model : ✅ /content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES/RESULTS/all-new-data-v1.yolov8_yolov8s-seg_trained/weights/best.pt
   - CNN Model  : ✅ /content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES/RESULTS/CNN_DenseNet121_Trained/best_v3_step2.keras
   - Workbook   : ✅ /content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES/DATASET_BUILDER/2_Manual_Records/manual_data.xlsx
   - Images Dir : ✅ /content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES/DATASET_BUILDER/1_Raw_Images

In [5]:
# [Section 6 & 7]: Validate canonical workbook and flat raw images
from rice_dataset.io.manual_records import load_manual_records
from rice_dataset.io.image_index import validate_flat_inventory

records, invalid_rows = load_manual_records(workbook_path)
if invalid_rows:
    preview = [f"{row['sample_id']}: {row['error']}" for row in invalid_rows[:5]]
    raise ValueError(f"{len(invalid_rows)} invalid workbook row(s): {preview}")

inventory = validate_flat_inventory(
    records,
    images_dir,
    prefix=config.id_prefix,
    digits=config.id_digits,
    require_exact_match=True,
)
print(
    f"✅ Input inventory: {inventory['record_count']} workbook rows, "
    f"{inventory['image_count']} flat images, "
    f"{inventory['unique_record_count']} unique Sample_ID values."
)

✅ Input inventory: 261 workbook rows, 261 flat images, 261 unique Sample_ID values.

In [6]:
# [Section 8]: Initialize Models (Once)
from rice_dataset.pipeline import DatasetExtractionPipeline

pipeline = DatasetExtractionPipeline(config)
pipeline.initialize_models()
print("✅ All deep learning models initialized on device.")

📦 Loading SAHI YOLO model from: /content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES/RESULTS/all-new-data-v1.yolov8_yolov8s-seg_trained/weights/best.pt...
Creating new Ultralytics Settings v0.0.8 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/usage/settings.
✅ SAHI YOLO model loaded successfully.
📦 Loading DenseNet121 CNN model from: /content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES/RESULTS/CNN_DenseNet121_Trained/best_v3_step2.keras...
📦 Đang nạp mô hình CNN từ: /content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES/RESULTS/CNN_DenseNet121_Trained/best_v3_step2.keras...
✅ Nạp mô hình CNN thành công!
✅ DenseNet121 CNN model loaded successfully.
✅ All deep learning models initialized on device.

In [7]:
# [Section 9 & 10]: Run Batch Extraction & Show Failure Summary
# Set limit=None to process all rows, or limit=5 for a quick test run
results = pipeline.run_batch(limit=None, export=True)

import pandas as pd
df_res = pd.DataFrame(results)

print("\n📊 QC Status Breakdown:")
display(df_res["QC_Status"].value_counts())

failed_rows = df_res[df_res["QC_Status"] != "PASS"]
if not failed_rows.empty:
    print("\n⚠️ Non-PASS Samples Summary:")
    display(failed_rows[["Sample_ID", "Image_Status", "QC_Status", "QC_Reason"]].head(20))

🚀 Starting batch extraction for 261 sample records...
Performing prediction on 63 slices.
[001/261] M0001 -> PASS [20.71s]
Performing prediction on 63 slices.
[002/261] M0002 -> PASS [9.98s]
Performing prediction on 63 slices.
[003/261] M0003 -> PASS [26.16s]
Performing prediction on 63 slices.
[004/261] M0004 -> PASS [5.28s]
Performing prediction on 63 slices.
[005/261] M0005 -> PASS [6.64s]
Performing prediction on 63 slices.
[006/261] M0006 -> PASS [5.38s]
Performing prediction on 63 slices.
[007/261] M0007 -> PASS [7.22s]
Performing prediction on 63 slices.
[008/261] M0008 -> PASS [5.39s]
Performing prediction on 63 slices.
[009/261] M0009 -> PASS [5.07s]
Performing prediction on 63 slices.
[010/261] M0010 -> PASS [7.27s]
Performing prediction on 221 slices.
[011/261] M0011 -> PASS [18.52s]
Performing prediction on 221 slices.
[012/261] M0012 -> PASS [15.87s]
Performing prediction on 221 slices.
[013/261] M0013 -> PASS [19.61s]
Performing prediction on 221 slices.
[014/261] M0014 -> PASS [16.71s]
Performing prediction on 221 slices.
[015/261] M0015 -> PASS [14.88s]
Performing prediction on 221 slices.
[016/261] M0016 -> PASS [23.30s]
Performing prediction on 221 slices.
[017/261] M0017 -> PASS [21.93s]
Performing prediction on 221 slices.
[018/261] M0018 -> PASS [21.68s]
Performing prediction on 221 slices.
[019/261] M0019 -> PASS [19.84s]
Performing prediction on 221 slices.
[020/261] M0020 -> PASS [16.81s]
Performing prediction on 221 slices.
[021/261] M0021 -> PASS [20.41s]
Performing prediction on 221 slices.
[022/261] M0022 -> PASS [17.45s]
Performing prediction on 221 slices.
[023/261] M0023 -> PASS [15.59s]
Performing prediction on 221 slices.
[024/261] M0024 -> PASS [19.31s]
Performing prediction on 221 slices.
[025/261] M0025 -> PASS [17.21s]
Performing prediction on 221 slices.
[026/261] M0026 -> PASS [16.60s]
Performing prediction on 221 slices.
[027/261] M0027 -> PASS [18.64s]
Performing prediction on 221 slices.
[028/261] M0028 -> PASS [20.07s]
Performing prediction on 221 slices.
[029/261] M0029 -> PASS [16.50s]
Performing prediction on 221 slices.
[030/261] M0030 -> PASS [20.61s]
Performing prediction on 221 slices.
[031/261] M0031 -> PASS [18.51s]
Performing prediction on 221 slices.
[032/261] M0032 -> PASS [17.76s]
Performing prediction on 63 slices.
[033/261] M0033 -> PASS [3.94s]
Performing prediction on 63 slices.
[034/261] M0034 -> PASS [3.11s]
Performing prediction on 63 slices.
[035/261] M0035 -> PASS [3.02s]
Performing prediction on 63 slices.
[036/261] M0036 -> PASS [3.40s]
Performing prediction on 63 slices.
[037/261] M0037 -> PASS [3.48s]
Performing prediction on 221 slices.
[038/261] M0038 -> PASS [15.85s]
Performing prediction on 221 slices.
[039/261] M0039 -> PASS [14.14s]
Performing prediction on 221 slices.
[040/261] M0040 -> PASS [15.70s]
Performing prediction on 221 slices.
[041/261] M0041 -> PASS [13.63s]
Performing prediction on 221 slices.
[042/261] M0042 -> PASS [15.79s]
Performing prediction on 221 slices.
[043/261] M0043 -> PASS [13.67s]
Performing prediction on 221 slices.
[044/261] M0044 -> PASS [13.52s]
Performing prediction on 221 slices.
[045/261] M0045 -> PASS [12.40s]
Performing prediction on 221 slices.
[046/261] M0046 -> PASS [14.10s]
Performing prediction on 221 slices.
[047/261] M0047 -> PASS [13.71s]
Performing prediction on 221 slices.
[048/261] M0048 -> PASS [12.34s]
Performing prediction on 221 slices.
[049/261] M0049 -> PASS [15.01s]
Performing prediction on 221 slices.
[050/261] M0050 -> PASS [13.33s]
Performing prediction on 221 slices.
[051/261] M0051 -> PASS [13.21s]
Performing prediction on 221 slices.
[052/261] M0052 -> PASS [15.73s]
Performing prediction on 221 slices.
[053/261] M0053 -> PASS [14.63s]
Performing prediction on 221 slices.
[054/261] M0054 -> PASS [14.88s]
Performing prediction on 221 slices.
[055/261] M0055 -> PASS [12.14s]
Performing prediction on 221 slices.
[056/261] M0056 -> PASS [14.52s]
Performing prediction on 221 slices.
[057/261] M0057 -> PASS [17.19s]
Performing prediction on 221 slices.
[058/261] M0058 -> PASS [13.41s]
Performing prediction on 221 slices.
[059/261] M0059 -> PASS [14.02s]
Performing prediction on 221 slices.
[060/261] M0060 -> PASS [13.34s]
Performing prediction on 221 slices.
[061/261] M0061 -> PASS [13.38s]
Performing prediction on 221 slices.
[062/261] M0062 -> PASS [14.08s]
Performing prediction on 221 slices.
[063/261] M0063 -> PASS [14.15s]
Performing prediction on 221 slices.
[064/261] M0064 -> PASS [13.09s]
Performing prediction on 221 slices.
[065/261] M0065 -> PASS [12.99s]
Performing prediction on 221 slices.
[066/261] M0066 -> PASS [12.92s]
Performing prediction on 221 slices.
[067/261] M0067 -> PASS [13.11s]
Performing prediction on 221 slices.
[068/261] M0068 -> PASS [13.58s]
Performing prediction on 221 slices.
[069/261] M0069 -> PASS [14.04s]
Performing prediction on 221 slices.
[070/261] M0070 -> PASS [13.53s]
Performing prediction on 221 slices.
[071/261] M0071 -> PASS [15.47s]
Performing prediction on 221 slices.
[072/261] M0072 -> PASS [13.73s]
Performing prediction on 221 slices.
[073/261] M0073 -> PASS [13.68s]
Performing prediction on 221 slices.
[074/261] M0074 -> PASS [12.75s]
Performing prediction on 221 slices.
[075/261] M0075 -> NO_CNN_WHOLE_GRAINS (CNN detected 0 whole grains at confidence threshold 0.9.) [13.54s]
Performing prediction on 221 slices.
[076/261] M0076 -> PASS [11.10s]
Performing prediction on 221 slices.
[077/261] M0077 -> PASS [12.45s]
Performing prediction on 221 slices.
[078/261] M0078 -> PASS [11.69s]
Performing prediction on 221 slices.
[079/261] M0079 -> PASS [14.87s]
Performing prediction on 221 slices.
[080/261] M0080 -> PASS [12.10s]
Performing prediction on 221 slices.
[081/261] M0081 -> PASS [11.91s]
Performing prediction on 221 slices.
[082/261] M0082 -> PASS [12.34s]
Performing prediction on 221 slices.
[083/261] M0083 -> PASS [13.49s]
Performing prediction on 221 slices.
[084/261] M0084 -> PASS [12.25s]
Performing prediction on 221 slices.
[085/261] M0085 -> PASS [11.04s]
Performing prediction on 221 slices.
[086/261] M0086 -> PASS [12.32s]
Performing prediction on 221 slices.
[087/261] M0087 -> PASS [12.96s]
Performing prediction on 221 slices.
[088/261] M0088 -> PASS [12.61s]
Performing prediction on 221 slices.
[089/261] M0089 -> PASS [13.78s]
Performing prediction on 221 slices.
[090/261] M0090 -> PASS [14.95s]
Performing prediction on 221 slices.
[091/261] M0091 -> PASS [15.64s]
Performing prediction on 221 slices.
[092/261] M0092 -> PASS [13.63s]
Performing prediction on 221 slices.
[093/261] M0093 -> PASS [14.10s]
Performing prediction on 221 slices.
[094/261] M0094 -> PASS [14.63s]
Performing prediction on 221 slices.
[095/261] M0095 -> PASS [13.70s]
Performing prediction on 221 slices.
[096/261] M0096 -> PASS [16.41s]
Performing prediction on 221 slices.
[097/261] M0097 -> PASS [12.65s]
Performing prediction on 221 slices.
[098/261] M0098 -> PASS [13.58s]
Performing prediction on 221 slices.
[099/261] M0099 -> PASS [13.63s]
Performing prediction on 221 slices.
[100/261] M0100 -> PASS [16.37s]
Performing prediction on 221 slices.
[101/261] M0101 -> PASS [16.44s]
Performing prediction on 221 slices.
[102/261] M0102 -> PASS [15.23s]
Performing prediction on 221 slices.
[103/261] M0103 -> PASS [14.93s]
Performing prediction on 221 slices.
[104/261] M0104 -> PASS [14.95s]
Performing prediction on 221 slices.
[105/261] M0105 -> PASS [13.51s]
Performing prediction on 221 slices.
[106/261] M0106 -> PASS [15.29s]
Performing prediction on 221 slices.
[107/261] M0107 -> PASS [13.56s]
Performing prediction on 221 slices.
[108/261] M0108 -> PASS [13.08s]
Performing prediction on 221 slices.
[109/261] M0109 -> PASS [13.77s]
Performing prediction on 221 slices.
[110/261] M0110 -> PASS [13.37s]
Performing prediction on 221 slices.
[111/261] M0111 -> PASS [13.35s]
Performing prediction on 221 slices.
[112/261] M0112 -> PASS [14.54s]
Performing prediction on 221 slices.
[113/261] M0113 -> PASS [14.64s]
Performing prediction on 221 slices.
[114/261] M0114 -> PASS [16.45s]
Performing prediction on 221 slices.
[115/261] M0115 -> PASS [17.38s]
Performing prediction on 221 slices.
[116/261] M0116 -> PASS [14.82s]
Performing prediction on 221 slices.
[117/261] M0117 -> PASS [18.46s]
Performing prediction on 221 slices.
[118/261] M0118 -> PASS [16.45s]
Performing prediction on 221 slices.
[119/261] M0119 -> PASS [14.66s]
Performing prediction on 221 slices.
[120/261] M0120 -> PASS [15.88s]
Performing prediction on 221 slices.
[121/261] M0121 -> PASS [16.28s]
Performing prediction on 221 slices.
[122/261] M0122 -> PASS [16.24s]
Performing prediction on 221 slices.
[123/261] M0123 -> PASS [15.86s]
Performing prediction on 221 slices.
[124/261] M0124 -> PASS [18.19s]
Performing prediction on 221 slices.
[125/261] M0125 -> PASS [17.34s]
Performing prediction on 221 slices.
[126/261] M0126 -> PASS [15.97s]
Performing prediction on 221 slices.
[127/261] M0127 -> PASS [20.64s]
Performing prediction on 221 slices.
[128/261] M0128 -> PASS [16.93s]
Performing prediction on 221 slices.
[129/261] M0129 -> PASS [16.30s]
Performing prediction on 221 slices.
[130/261] M0130 -> PASS [19.43s]
Performing prediction on 221 slices.
[131/261] M0131 -> PASS [17.63s]
Performing prediction on 221 slices.
[132/261] M0132 -> PASS [18.86s]
Performing prediction on 221 slices.
[133/261] M0133 -> PASS [19.13s]
Performing prediction on 221 slices.
[134/261] M0134 -> PASS [17.38s]
Performing prediction on 221 slices.
[135/261] M0135 -> PASS [20.33s]
Performing prediction on 221 slices.
[136/261] M0136 -> PASS [18.73s]
Performing prediction on 221 slices.
[137/261] M0137 -> PASS [18.85s]
Performing prediction on 221 slices.
[138/261] M0138 -> PASS [17.33s]
Performing prediction on 221 slices.
[139/261] M0139 -> PASS [17.28s]
Performing prediction on 221 slices.
[140/261] M0140 -> PASS [19.18s]
Performing prediction on 221 slices.
[141/261] M0141 -> PASS [17.94s]
Performing prediction on 221 slices.
[142/261] M0142 -> PASS [19.66s]
Performing prediction on 221 slices.
[143/261] M0143 -> PASS [19.52s]
Performing prediction on 221 slices.
[144/261] M0144 -> PASS [13.50s]
Performing prediction on 221 slices.
[145/261] M0145 -> PASS [17.24s]
Performing prediction on 221 slices.
[146/261] M0146 -> PASS [18.19s]
Performing prediction on 221 slices.
[147/261] M0147 -> PASS [16.42s]
Performing prediction on 221 slices.
[148/261] M0148 -> PASS [17.92s]
Performing prediction on 221 slices.
[149/261] M0149 -> PASS [21.61s]
Performing prediction on 221 slices.
[150/261] M0150 -> PASS [22.61s]
Performing prediction on 221 slices.
[151/261] M0151 -> PASS [14.88s]
Performing prediction on 221 slices.
[152/261] M0152 -> PASS [16.22s]
Performing prediction on 221 slices.
[153/261] M0153 -> PASS [16.15s]
Performing prediction on 221 slices.
[154/261] M0154 -> PASS [16.61s]
Performing prediction on 221 slices.
[155/261] M0155 -> PASS [13.84s]
Performing prediction on 221 slices.
[156/261] M0156 -> PASS [19.55s]
Performing prediction on 221 slices.
[157/261] M0157 -> PASS [17.19s]
Performing prediction on 221 slices.
[158/261] M0158 -> PASS [18.20s]
Performing prediction on 221 slices.
[159/261] M0159 -> PASS [16.67s]
Performing prediction on 221 slices.
[160/261] M0160 -> PASS [17.36s]
Performing prediction on 221 slices.
[161/261] M0161 -> PASS [18.51s]
Performing prediction on 221 slices.
[162/261] M0162 -> PASS [18.07s]
Performing prediction on 221 slices.
[163/261] M0163 -> PASS [19.72s]
Performing prediction on 221 slices.
[164/261] M0164 -> PASS [17.49s]
Performing prediction on 221 slices.
[165/261] M0165 -> PASS [18.17s]
Performing prediction on 221 slices.
[166/261] M0166 -> PASS [16.81s]
Performing prediction on 221 slices.
[167/261] M0167 -> PASS [17.63s]
Performing prediction on 221 slices.
[168/261] M0168 -> PASS [17.90s]
Performing prediction on 221 slices.
[169/261] M0169 -> PASS [15.30s]
Performing prediction on 221 slices.
[170/261] M0170 -> PASS [17.06s]
Performing prediction on 221 slices.
[171/261] M0171 -> PASS [18.44s]
Performing prediction on 221 slices.
[172/261] M0172 -> PASS [16.16s]
Performing prediction on 221 slices.
[173/261] M0173 -> PASS [20.32s]
Performing prediction on 221 slices.
[174/261] M0174 -> PASS [17.51s]
Performing prediction on 221 slices.
[175/261] M0175 -> PASS [17.05s]
Performing prediction on 221 slices.
[176/261] M0176 -> PASS [18.11s]
Performing prediction on 221 slices.
[177/261] M0177 -> PASS [17.45s]
Performing prediction on 221 slices.
[178/261] M0178 -> PASS [18.77s]
Performing prediction on 221 slices.
[179/261] M0179 -> PASS [15.11s]
Performing prediction on 221 slices.
[180/261] M0180 -> PASS [17.34s]
Performing prediction on 221 slices.
[181/261] M0181 -> PASS [22.32s]
Performing prediction on 221 slices.
[182/261] M0182 -> PASS [20.18s]
Performing prediction on 221 slices.
[183/261] M0183 -> PASS [19.74s]
Performing prediction on 221 slices.
[184/261] M0184 -> PASS [18.55s]
Performing prediction on 221 slices.
[185/261] M0185 -> PASS [17.05s]
Performing prediction on 221 slices.
[186/261] M0186 -> PASS [19.49s]
Performing prediction on 221 slices.
[187/261] M0187 -> PASS [17.23s]
Performing prediction on 221 slices.
[188/261] M0188 -> PASS [20.37s]
Performing prediction on 221 slices.
[189/261] M0189 -> PASS [18.52s]
Performing prediction on 221 slices.
[190/261] M0190 -> PASS [20.86s]
Performing prediction on 221 slices.
[191/261] M0191 -> PASS [20.44s]
Performing prediction on 221 slices.
[192/261] M0192 -> PASS [18.48s]
Performing prediction on 221 slices.
[193/261] M0193 -> PASS [16.37s]
Performing prediction on 221 slices.
[194/261] M0194 -> PASS [18.42s]
Performing prediction on 221 slices.
[195/261] M0195 -> PASS [20.11s]
Performing prediction on 221 slices.
[196/261] M0196 -> PASS [16.48s]
Performing prediction on 221 slices.
[197/261] M0197 -> PASS [17.87s]
Performing prediction on 221 slices.
[198/261] M0198 -> PASS [16.22s]
Performing prediction on 221 slices.
[199/261] M0199 -> PASS [17.88s]
Performing prediction on 221 slices.
[200/261] M0200 -> PASS [19.47s]
Performing prediction on 221 slices.
[201/261] M0201 -> PASS [19.71s]
Performing prediction on 221 slices.
[202/261] M0202 -> PASS [17.28s]
Performing prediction on 221 slices.
[203/261] M0203 -> PASS [19.69s]
[204/261] M0204 -> CONTAINER_DETECTION_FAILED (Container detection error: Tỉ lệ mép trong/mép ngoài (0.37) nhỏ bất thường về mặt vật lý (ngưỡng 0.50). detect_type='radial_vote_pair' — kiểm tra lại wall_thickness_mm.) [0.93s]
Performing prediction on 221 slices.
[205/261] M0205 -> PASS [25.99s]
Performing prediction on 221 slices.
[206/261] M0206 -> PASS [18.03s]
Performing prediction on 221 slices.
[207/261] M0207 -> PASS [19.08s]
Performing prediction on 221 slices.
[208/261] M0208 -> PASS [20.57s]
Performing prediction on 221 slices.
[209/261] M0209 -> PASS [20.77s]
Performing prediction on 221 slices.
[210/261] M0210 -> PASS [18.37s]
Performing prediction on 221 slices.
[211/261] M0211 -> PASS [20.12s]
Performing prediction on 221 slices.
[212/261] M0212 -> PASS [22.14s]
Performing prediction on 221 slices.
[213/261] M0213 -> PASS [19.77s]
Performing prediction on 221 slices.
[214/261] M0214 -> PASS [18.70s]
Performing prediction on 221 slices.
[215/261] M0215 -> PASS [22.70s]
Performing prediction on 221 slices.
[216/261] M0216 -> PASS [18.01s]
Performing prediction on 221 slices.
[217/261] M0217 -> PASS [19.07s]
Performing prediction on 221 slices.
[218/261] M0218 -> PASS [19.76s]
Performing prediction on 221 slices.
[219/261] M0219 -> PASS [21.98s]
Performing prediction on 221 slices.
[220/261] M0220 -> PASS [19.64s]
Performing prediction on 221 slices.
[221/261] M0221 -> PASS [18.99s]
Performing prediction on 221 slices.
[222/261] M0222 -> PASS [18.51s]
Performing prediction on 221 slices.
[223/261] M0223 -> PASS [18.54s]
Performing prediction on 221 slices.
[224/261] M0224 -> PASS [22.72s]
Performing prediction on 221 slices.
[225/261] M0225 -> PASS [20.73s]
Performing prediction on 221 slices.
[226/261] M0226 -> PASS [19.37s]
Performing prediction on 221 slices.
[227/261] M0227 -> PASS [21.91s]
Performing prediction on 221 slices.
[228/261] M0228 -> PASS [20.75s]
Performing prediction on 221 slices.
[229/261] M0229 -> PASS [17.44s]
Performing prediction on 221 slices.
[230/261] M0230 -> PASS [21.81s]
[231/261] M0231 -> CONTAINER_DETECTION_FAILED (Container detection error: Không có vòng nào vừa được đủ tia bình chọn (>= 108/360 tia) vừa bao quanh được khối lúa (đường kính >= 1.90 x 182.1px). Đây thường là dấu hiệu viền ly bị phản chiếu che mất phần lớn chu vi: thử hạ min_rim_rays_ratio, hoặc chụp lại với ánh sáng tán xạ.) [0.90s]
Performing prediction on 221 slices.
[232/261] M0232 -> PASS [17.69s]
Performing prediction on 221 slices.
[233/261] M0233 -> PASS [22.24s]
Performing prediction on 221 slices.
[234/261] M0234 -> PASS [23.82s]
Performing prediction on 221 slices.
[235/261] M0235 -> PASS [19.12s]
Performing prediction on 221 slices.
[236/261] M0236 -> PASS [21.61s]
Performing prediction on 221 slices.
[237/261] M0237 -> PASS [20.55s]
Performing prediction on 221 slices.
[238/261] M0238 -> PASS [18.33s]
Performing prediction on 221 slices.
[239/261] M0239 -> PASS [22.70s]
Performing prediction on 221 slices.
[240/261] M0240 -> PASS [19.49s]
Performing prediction on 221 slices.
[241/261] M0241 -> PASS [22.97s]
Performing prediction on 221 slices.
[242/261] M0242 -> PASS [18.23s]
Performing prediction on 221 slices.
[243/261] M0243 -> PASS [21.71s]
Performing prediction on 221 slices.
[244/261] M0244 -> PASS [22.09s]
Performing prediction on 221 slices.
[245/261] M0245 -> PASS [23.68s]
Performing prediction on 221 slices.
[246/261] M0246 -> PASS [23.35s]
Performing prediction on 221 slices.
[247/261] M0247 -> PASS [22.36s]
Performing prediction on 221 slices.
[248/261] M0248 -> PASS [24.85s]
Performing prediction on 221 slices.
[249/261] M0249 -> PASS [20.32s]
Performing prediction on 221 slices.
[250/261] M0250 -> PASS [22.89s]
Performing prediction on 221 slices.
[251/261] M0251 -> PASS [21.15s]
Performing prediction on 221 slices.
[252/261] M0252 -> PASS [20.65s]
Performing prediction on 221 slices.
[253/261] M0253 -> PASS [22.62s]
Performing prediction on 221 slices.
[254/261] M0254 -> PASS [20.34s]
Performing prediction on 221 slices.
[255/261] M0255 -> PASS [21.45s]
Performing prediction on 221 slices.
[256/261] M0256 -> PASS [22.03s]
Performing prediction on 221 slices.
[257/261] M0257 -> PASS [22.65s]
Performing prediction on 221 slices.
[258/261] M0258 -> PASS [28.82s]
Performing prediction on 221 slices.
[259/261] M0259 -> PASS [21.61s]
[260/261] M0260 -> CONTAINER_DETECTION_FAILED (Container detection error: Không có vòng nào vừa được đủ tia bình chọn (>= 108/360 tia) vừa bao quanh được khối lúa (đường kính >= 1.90 x 195.1px). Đây thường là dấu hiệu viền ly bị phản chiếu che mất phần lớn chu vi: thử hạ min_rim_rays_ratio, hoặc chụp lại với ánh sáng tán xạ.) [0.94s]
Performing prediction on 221 slices.
[261/261] M0261 -> PASS [24.78s]
============================================================
🏁 Batch extraction complete in 4346.2s.
   Total rows: 261 | PASS: 257 | Non-PASS: 4
============================================================
💾 Exported datasets:
   - Audit CSV (261 rows): /content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES/DATASET_BUILDER/3_AI_Extracted/ai_extracted_dataset.csv
   - Final CSV (257 rows): /content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES/DATASET_BUILDER/4_Final_Dataset/final_regression_dataset.csv
   - Final XLSX (257 rows): /content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES/DATASET_BUILDER/4_Final_Dataset/final_regression_dataset.xlsx

📊 QC Status Breakdown:

QC_Status
PASS                          257
CONTAINER_DETECTION_FAILED      3
NO_CNN_WHOLE_GRAINS             1
Name: count, dtype: int64

⚠️ Non-PASS Samples Summary:

,Sample_ID,Image_Status,QC_Status,QC_Reason
74,M0075,FOUND,NO_CNN_WHOLE_GRAINS,CNN detected 0 whole grains at confidence thre...
203,M0204,FOUND,CONTAINER_DETECTION_FAILED,Container detection error: Tỉ lệ mép trong/mép...
230,M0231,FOUND,CONTAINER_DETECTION_FAILED,Container detection error: Không có vòng nào v...
259,M0260,FOUND,CONTAINER_DETECTION_FAILED,Container detection error: Không có vòng nào v...

In [8]:
# [Section 11]: Verify canonical export datasets
from rice_dataset.contracts import CANONICAL_COLUMNS, QCStatus

audit_p = config.get_resolved_audit_output_path()
final_csv_p = config.get_resolved_final_csv_path()
final_xlsx_p = config.get_resolved_final_xlsx_path()

df_audit = pd.read_csv(audit_p)
df_final = pd.read_csv(final_csv_p)
df_final_xlsx = pd.read_excel(final_xlsx_p)

for label, frame in (
    ("audit CSV", df_audit),
    ("training CSV", df_final),
    ("training XLSX", df_final_xlsx),
):
    assert frame.columns.tolist() == CANONICAL_COLUMNS, (
        f"{label}: export columns differ from the {len(CANONICAL_COLUMNS)}-column contract"
    )

pass_count = sum(row["QC_Status"] == QCStatus.PASS for row in results)
assert len(df_audit) == len(results), "Audit row count differs from batch results"
assert len(df_final) == pass_count, "Training CSV row count differs from PASS results"
assert len(df_final_xlsx) == pass_count, "Training XLSX row count differs from PASS results"
print(
    f"✅ Export contract: {len(CANONICAL_COLUMNS)} columns; "
    f"{len(df_audit)} audit rows; {pass_count} training rows."
)

✅ Export contract: 47 columns; 261 audit rows; 257 training rows.

In [9]:
# [Section 12]: Static and contract parity check
import subprocess

subprocess.run(
    [
        sys.executable,
        str(PROJECT_ROOT / "DATASET_BUILDER/scripts/verify_pipeline_parity.py"),
        "--static",
    ],
    cwd=PROJECT_ROOT,
    check=True,
)

CompletedProcess(args=['/usr/bin/python3', '/content/drive/MyDrive/NGHIÊN CỨU KHOA HỌC/GROUP_MEMBERS/NGUYEN MINH TRI/MAIN_SOURCES/DATASET_BUILDER/scripts/verify_pipeline_parity.py', '--static'], returncode=0)